
"""Manejo de excepciones"""
"""Analizando el comportamiento del try except"""

try:
    val1 = 2/0
except:
    print("Entró el except, ha ocurrido una excepcion")
else:
    print("Entró al else, no ha ocurrido ninguna excepcion")




